apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talos
resources:
  - namespace.yaml
  - secret.example.yaml
  - control-plane-deployment.yaml
  - control-plane-service.yaml
  # Apply postgres.example.yaml only for development/testing.
  # - postgres.example.yaml
  # - ingress.example.yaml
  # - worker.example.yaml
